CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "status" boolean DEFAULT false,
  "phone_id" int,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "phones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone" varchar(20) UNIQUE NOT NULL,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "user_id" int,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "price" int DEFAULT 0,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "course_id" int,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

ALTER TABLE "phones" ADD FOREIGN KEY ("id") REFERENCES "users" ("phone_id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
